Make various misc changes

diff --git a/.bin/urxvt-connect b/.bin/urxvt-connect
--- a/.bin/urxvt-connect
+++ b/.bin/urxvt-connect
@@ -1,7 +1,12 @@
 #!/bin/bash
 
-if ! urxvtc "$@"
+# URxvtd:
+# 	-q : quiet.
+# 	-o : open display.
+# 	-f : fork (exit script without hanging).
+
+if ! urxvtc "$@" # Attempt to connect. On failure:
 then
-	urxvtd -q -o -f
+	urxvtd -q -o -f 
 	urxvtc "$@"
 fi
